"""add db

Revision ID: 035f9b89cf2d
Revises: d803252603b0
Create Date: 2025-01-27 16:10:39.440764

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '035f9b89cf2d'
down_revision = 'd803252603b0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('fri', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user', sa.String(), nullable=False))

    with op.batch_alter_table('inventry', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user', sa.String(), nullable=False))

    with op.batch_alter_table('menu', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user', sa.String(), nullable=False))

    with op.batch_alter_table('mon', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user', sa.String(), nullable=False))

    with op.batch_alter_table('prediction', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user', sa.String(), nullable=False))

    with op.batch_alter_table('sat', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user', sa.String(), nullable=False))

    with op.batch_alter_table('sun', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user', sa.String(), nullable=False))

    with op.batch_alter_table('thu', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user', sa.String(), nullable=False))

    with op.batch_alter_table('tue', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user', sa.String(), nullable=False))

    with op.batch_alter_table('wed', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user', sa.String(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('wed', schema=None) as batch_op:
        batch_op.drop_column('user')

    with op.batch_alter_table('tue', schema=None) as batch_op:
        batch_op.drop_column('user')

    with op.batch_alter_table('thu', schema=None) as batch_op:
        batch_op.drop_column('user')

    with op.batch_alter_table('sun', schema=None) as batch_op:
        batch_op.drop_column('user')

    with op.batch_alter_table('sat', schema=None) as batch_op:
        batch_op.drop_column('user')

    with op.batch_alter_table('prediction', schema=None) as batch_op:
        batch_op.drop_column('user')

    with op.batch_alter_table('mon', schema=None) as batch_op:
        batch_op.drop_column('user')

    with op.batch_alter_table('menu', schema=None) as batch_op:
        batch_op.drop_column('user')

    with op.batch_alter_table('inventry', schema=None) as batch_op:
        batch_op.drop_column('user')

    with op.batch_alter_table('fri', schema=None) as batch_op:
        batch_op.drop_column('user')

    # ### end Alembic commands ###
