"""add db

Revision ID: 16690d6172a3
Revises: 21635954b213
Create Date: 2025-01-28 03:10:01.785647

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '16690d6172a3'
down_revision = '21635954b213'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('wed')
    op.drop_table('sun')
    op.drop_table('tue')
    op.drop_table('thu')
    op.drop_table('fri')
    op.drop_table('mon')
    op.drop_table('sat')
    with op.batch_alter_table('prediction', schema=None) as batch_op:
        batch_op.add_column(sa.Column('weekday', sa.String(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('prediction', schema=None) as batch_op:
        batch_op.drop_column('weekday')

    op.create_table('sat',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('groop', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('num', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('user', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='sat_pkey')
    )
    op.create_table('mon',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('groop', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('num', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('user', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='mon_pkey')
    )
    op.create_table('fri',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('groop', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('num', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('user', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='fri_pkey')
    )
    op.create_table('thu',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('groop', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('num', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('user', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='thu_pkey')
    )
    op.create_table('tue',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('groop', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('num', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('user', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='tue_pkey')
    )
    op.create_table('sun',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('groop', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('num', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('user', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='sun_pkey')
    )
    op.create_table('wed',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('groop', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('num', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('user', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='wed_pkey')
    )
    # ### end Alembic commands ###
