"""add db

Revision ID: 21635954b213
Revises: 5fdca44fd8a7
Create Date: 2025-01-28 00:13:46.288847

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '21635954b213'
down_revision = '5fdca44fd8a7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('menu', schema=None) as batch_op:
        batch_op.drop_column('num')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('menu', schema=None) as batch_op:
        batch_op.add_column(sa.Column('num', sa.INTEGER(), autoincrement=False, nullable=False))

    # ### end Alembic commands ###
