"""add db

Revision ID: d803252603b0
Revises: 
Create Date: 2025-01-26 04:50:14.948445

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd803252603b0'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fri',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('groop', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('num', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('mon',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('groop', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('num', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('prediction',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('groop', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('num', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sat',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('groop', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('num', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sun',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('groop', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('num', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('thu',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('groop', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('num', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tue',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('groop', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('num', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('wed',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('groop', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('num', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('inventry', schema=None) as batch_op:
        batch_op.add_column(sa.Column('groop', sa.String(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('inventry', schema=None) as batch_op:
        batch_op.drop_column('groop')

    op.drop_table('wed')
    op.drop_table('user')
    op.drop_table('tue')
    op.drop_table('thu')
    op.drop_table('sun')
    op.drop_table('sat')
    op.drop_table('prediction')
    op.drop_table('mon')
    op.drop_table('fri')
    # ### end Alembic commands ###
